# Generated by Django 5.2.4 on 2025-08-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
