# Generated by Django 5.2.4 on 2025-08-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pin',
        ),
    ]
