# Generated by Django 5.2.1 on 2025-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=30)),
                ('nivel', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('pergunta', models.TextField()),
                ('resposta_0', models.TextField()),
                ('resposta_1', models.TextField()),
                ('resposta_2', models.TextField()),
                ('resposta_3', models.TextField()),
                ('gabarito', models.IntegerField()),
                ('tema', models.IntegerField()),
                ('idioma', models.CharField(max_length=5)),
                ('ilustracao', models.CharField(max_length=256)),
            ],
        ),
    ]
