# Generated by Django 5.2.5 on 2025-09-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0002_alter_perguntas_ilustracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntas',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
