# Generated by Django 5.2.5 on 2025-09-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0003_perguntas_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perguntas',
            old_name='explanation',
            new_name='Explicação',
        ),
    ]
