# Generated by Django 5.2.5 on 2025-09-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0004_rename_explanation_perguntas_explicação'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perguntas',
            old_name='Explicação',
            new_name='explicacao',
        ),
    ]
