# Generated by Django 5.2.5 on 2025-08-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_player', models.IntegerField()),
                ('nickname', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('tempo', models.IntegerField()),
                ('nivel_max', models.IntegerField()),
                ('modulos', models.CharField(max_length=100)),
            ],
        ),
    ]
